// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "auto-geo-ingestion/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// HealthService is an autogenerated mock type for the HealthService type
type HealthService struct {
	mock.Mock
}

// GetHealth provides a mock function with given fields: ctx
func (_m *HealthService) GetHealth(ctx context.Context) (domain.Health, error) {
	ret := _m.Called(ctx)

	var r0 domain.Health
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (domain.Health, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) domain.Health); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(domain.Health)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHealthService creates a new instance of HealthService. It also registers a testing interface on the mock
// and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthService {
	mockObj := &HealthService{}
	mockObj.Mock.Test(t)

	t.Cleanup(func() { mockObj.AssertExpectations(t) })

	return mockObj
}
